[package]
name = "day5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
aoc = { version = "0.1.0", path = "../aoc" }
argh = "0.1.12"
nom = "7.1.3"
rangemap = "1.4.0"
